# Generated by Django 4.2.2 on 2023-06-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(blank=True, max_length=200)),
                ('Currency', models.CharField(blank=True, max_length=20)),
                ('BillingMethod', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.CharField(blank=True, max_length=200)),
                ('FirstName', models.CharField(blank=True, max_length=200)),
                ('LastName', models.CharField(blank=True, max_length=200)),
                ('Phone', models.SmallIntegerField()),
                ('Mobile', models.SmallIntegerField()),
                ('Fax', models.CharField(blank=True, max_length=200)),
                ('ClientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
